name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'scripts/**'
      - 'Dockerfile'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.1
        id: bump_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pvs3:${{ steps.bump_version.outputs.new_tag }},${{ secrets.DOCKERHUB_USERNAME }}/pvs3:latest
          push: true

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.bump_version.outputs.new_tag }}
          name: Release ${{ steps.bump_version.outputs.new_tag }}
          body: ${{ steps.bump_version.outputs.changelog }}
